### ISSUE TITLE
Format NN fails on foreign-key constraint violation (cannot truncate table)

### ISSUE THREAD

**Issue by jimdowling** [hopshadoop/hops#30]
I'm not sure how to repeat this, but I started the NN and DN. There was some problem with the DN. I had to re-format the NN, then got this:

INFO: Created cluster connection '10.0.2.15:1186 ' with node id 0, mgm timeout 30,000.
15/05/02 06:50:29 INFO hikari.HikariDataSource: HikariCP pool HikariPool-0 is starting.
15/05/02 06:50:33 ERROR ndb.ClusterjConnector: Cannot truncate a table referenced in a foreign key constraint ()
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Cannot truncate a table referenced in a foreign key constraint ()
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3609)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2002)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2624)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2127)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2427)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2345)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2330)
	at com.zaxxer.hikari.proxy.PreparedStatementJavassistProxy.executeUpdate(PreparedStatementJavassistProxy.java)
	at io.hops.metadata.ndb.mysqlserver.MysqlServerConnector.truncateTable(MysqlServerConnector.java:155)
	at io.hops.metadata.ndb.mysqlserver.MysqlServerConnector.truncateTable(MysqlServerConnector.java:126)
	at io.hops.metadata.ndb.ClusterjConnector.truncate(ClusterjConnector.java:568)
	at io.hops.metadata.ndb.ClusterjConnector.format(ClusterjConnector.java:531)
	at io.hops.metadata.ndb.ClusterjConnector.format(ClusterjConnector.java:332)
	at io.hops.metadata.ndb.ClusterjConnector.formatStorageNonTransactional(ClusterjConnector.java:328)
	at io.hops.metadata.HdfsStorageFactory.formatStorageNonTransactional(HdfsStorageFactory.java:309)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.format(NameNode.java:734)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:893)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.main(NameNode.java:973)
15/05/02 06:50:36 ERROR ndb.ClusterjConnector: Cannot truncate a table referenced in a foreign key constraint ()
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Cannot truncate a table referenced in a foreign key constraint ()
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3609)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2002)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2624)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2127)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2427)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2345)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2330)
	at com.zaxxer.hikari.proxy.PreparedStatementJavassistProxy.executeUpdate(PreparedStatementJavassistProxy.java)
	at io.hops.metadata.ndb.mysqlserver.MysqlServerConnector.truncateTable(MysqlServerConnector.java:155)
	at io.hops.metadata.ndb.mysqlserver.MysqlServerConnector.truncateTable(MysqlServerConnector.java:126)
	at io.hops.metadata.ndb.ClusterjConnector.truncate(ClusterjConnector.java:568)
	at io.hops.metadata.ndb.ClusterjConnector.format(ClusterjConnector.java:531)
	at io.hops.metadata.ndb.ClusterjConnector.format(ClusterjConnector.java:332)
	at io.hops.metadata.ndb.ClusterjConnector.formatStorageNonTransactional(ClusterjConnector.java:328)
	at io.hops.metadata.HdfsStorageFactory.formatStorageNonTransactional(HdfsStorageFactory.java:309)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.format(NameNode.java:734)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:893)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.main(NameNode.java:973)
15/05/02 06:50:39 ERROR ndb.ClusterjConnector: Cannot truncate a table referenced in a foreign key constraint ()
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Cannot truncate a table referenced in a foreign key constraint ()
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3609)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2002)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2624)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2127)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2427)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2345)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2330)
	at com.zaxxer.hikari.proxy.PreparedStatementJavassistProxy.executeUpdate(PreparedStatementJavassistProxy.java)
	at io.hops.metadata.ndb.mysqlserver.MysqlServerConnector.truncateTable(MysqlServerConnector.java:155)
	at io.hops.metadata.ndb.mysqlserver.MysqlServerConnector.truncateTable(MysqlServerConnector.java:126)
	at io.hops.metadata.ndb.ClusterjConnector.truncate(ClusterjConnector.java:568)
	at io.hops.metadata.ndb.ClusterjConnector.format(ClusterjConnector.java:531)
	at io.hops.metadata.ndb.ClusterjConnector.format(ClusterjConnector.java:332)
	at io.hops.metadata.ndb.ClusterjConnector.formatStorageNonTransactional(ClusterjConnector.java:328)
	at io.hops.metadata.HdfsStorageFactory.formatStorageNonTransactional(HdfsStorageFactory.java:309)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.format(NameNode.java:734)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:893)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.main(NameNode.java:973)
15/05/02 06:50:43 ERROR ndb.ClusterjConnector: Cannot truncate a table referenced in a foreign key constraint ()
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Cannot truncate a table referenced in a foreign key constraint ()
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3609)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2002)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2624)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2127)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2427)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2345)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2330)
	at com.zaxxer.hikari.proxy.PreparedStatementJavassistProxy.executeUpdate(PreparedStatementJavassistProxy.java)
	at io.hops.metadata.ndb.mysqlserver.MysqlServerConnector.truncateTable(MysqlServerConnector.java:155)
	at io.hops.metadata.ndb.mysqlserver.MysqlServerConnector.truncateTable(MysqlServerConnector.java:126)
	at io.hops.metadata.ndb.ClusterjConnector.truncate(ClusterjConnector.java:568)
	at io.hops.metadata.ndb.ClusterjConnector.format(ClusterjConnector.java:531)
	at io.hops.metadata.ndb.ClusterjConnector.format(ClusterjConnector.java:332)
	at io.hops.metadata.ndb.ClusterjConnector.formatStorageNonTransactional(ClusterjConnector.java:328)
	at io.hops.metadata.HdfsStorageFactory.formatStorageNonTransactional(HdfsStorageFactory.java:309)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.format(NameNode.java:734)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:893)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.main(NameNode.java:973)
15/05/02 06:50:46 ERROR ndb.ClusterjConnector: Cannot truncate a table referenced in a foreign key constraint ()
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Cannot truncate a table referenced in a foreign key constraint ()
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3609)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2002)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2624)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2127)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2427)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2345)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2330)
	at com.zaxxer.hikari.proxy.PreparedStatementJavassistProxy.executeUpdate(PreparedStatementJavassistProxy.java)
	at io.hops.metadata.ndb.mysqlserver.MysqlServerConnector.truncateTable(MysqlServerConnector.java:155)
	at io.hops.metadata.ndb.mysqlserver.MysqlServerConnector.truncateTable(MysqlServerConnector.java:126)
	at io.hops.metadata.ndb.ClusterjConnector.truncate(ClusterjConnector.java:568)
	at io.hops.metadata.ndb.ClusterjConnector.format(ClusterjConnector.java:531)
	at io.hops.metadata.ndb.ClusterjConnector.format(ClusterjConnector.java:332)
	at io.hops.metadata.ndb.ClusterjConnector.formatStorageNonTransactional(ClusterjConnector.java:328)
	at io.hops.metadata.HdfsStorageFactory.formatStorageNonTransactional(HdfsStorageFactory.java:309)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.format(NameNode.java:734)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:893)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.main(NameNode.java:973)
15/05/02 06:50:46 INFO common.StorageInfo: Added new entry to storage info. nsid:dfs.name.space.id CID:CID-02c8a3ba-5c98-4572-8da8-e9e6bf2a3c12 pbid:BP-12934383-10.0.2.15-1430549446256
15/05/02 06:50:46 INFO util.ExitUtil: Exiting with status 0
15/05/02 06:50:46 INFO namenode.NameNode: SHUTDOWN_MSG: 
/*********************************************************

**Comment by steffengr** [comment]
Isn't that the same old problem that should have been fixed by a path by Gautier? What version of the code were you using?

**Comment by jimdowling** [comment]
I forgot to mention that I use the "-force" option when formatting the namenode. Formatting appears to work fine without the "-force" option, but fails when "-force" is added.

**Comment by steffengr** [comment]
The -force options causes a truncate on the table. There are currently issues with truncating and the use of foreign keys. Deactivating foreign keys before truncating could possibly be a solution for this.

**Comment by berthoug** [comment]
ndb does not support deactivating foreign keys, I'm searching for another solution.

**Comment by jimdowling** [comment]
You can drop foreign keys using the MySQL server using DDL sent in JDBC.
Messy.
Is it not easier to drop the DB and reinitialize it?

On Tue, May 5, 2015 at 3:57 PM, Gautier Berthou <notifications@github.com>
wrote:

> ndb does not support deactivating foreign keys, I'm searching for another
> solution.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hopshadoop/hops/issues/30#issuecomment-99085031>.
>



-- 
regards,
--------------
Jim Dowling, PhD,
Senior Scientist, SICS - Swedish ICT
Associate Prof, KTH -Royal Institute of Technology

**Comment by berthoug** [comment]
I thought about these two solutions.

The first one is very messy: for each table T we want to truncate we need to get the list of tables that have a foreign key toward T, to drop these foreign keys, to truncate T and then to recreate the foreign keys one by one.

The second one can be done by asking the path to the schema with the "-force" option. But, I'm wondering if it would not be simpler to remove the "-force" option and to tell the administrator that if they want to do that they can drop the DB and reinitialize it themselves before to run format. I think that force is an option we added for our database system.

**Comment by jimdowling** [comment]
Why don't we just include the schema definition in the distribution. Then the format command can use JDBC to drop the database and recreate the database?

**Comment by berthoug** [comment]
Salman has implemented a function that drop the database and recreate it, but formatStorageNonTransactional (which does truncate) is still there and is still called by the namenode. Is there a reason not to replace it by dropAndRecreateDB?

**Comment by jimdowling** [comment]
Fixed.
