### ISSUE TITLE
Heartbeat RPC getting too big for DB

### ISSUE THREAD

**Issue by stigviaene** [hopshadoop/hops#57]
Resulting in no container getting allocated. (And much more.)

	2015-06-26 11:59:50,235 WARN org.apache.hadoop.ipc.Server: IPC Server handler 23 on 8031, call org.apache.hadoop.yarn.server.api.ResourceTrackerPB.nodeHeartbeat from 193.10.66.125:49380 Call#68001 Retry#0: error: com.mysql.clusterj.ClusterJDatastoreException: For field rpc column rpc valueDelegate setBytes, error executing objectSetValue. Caused by com.mysql.clusterj.ClusterJUserException:Data length 16,703 too long. Column 'rpc' can only accept data of length 13,000.
	com.mysql.clusterj.ClusterJDatastoreException: For field rpc column rpc valueDelegate setBytes, error executing objectSetValue. Caused by com.mysql.clusterj.ClusterJUserException:Data length 16,703 too long. Column 'rpc' can only accept data of length 13,000.
		at com.mysql.clusterj.core.metadata.AbstractDomainFieldHandlerImpl.objectSetValue(AbstractDomainFieldHandlerImpl.java:289)
		at com.mysql.clusterj.tie.NdbRecordSmartValueHandlerImpl.set(NdbRecordSmartValueHandlerImpl.java:724)
		at com.mysql.clusterj.tie.NdbRecordSmartValueHandlerImpl.invoke(NdbRecordSmartValueHandlerImpl.java:750)
		at com.mysql.clusterj.core.metadata.$Proxy31.setrpc(Unknown Source)
		at io.hops.metadata.ndb.dalimpl.yarn.rmstatestore.RPCClusterJ.createPersistable(RPCClusterJ.java:174)
		at io.hops.metadata.ndb.dalimpl.yarn.rmstatestore.RPCClusterJ.add(RPCClusterJ.java:106)
		at io.hops.metadata.ndb.dalimpl.yarn.rmstatestore.RPCClusterJ.add(RPCClusterJ.java:41)
		at io.hops.metadata.util.RMUtilities$21.performTask(RMUtilities.java:756)
		at io.hops.transaction.handler.LightWeightRequestHandler.execute(LightWeightRequestHandler.java:50)
		at io.hops.transaction.handler.RequestHandler.handle(RequestHandler.java:52)
		at io.hops.transaction.handler.RequestHandler.handle(RequestHandler.java:47)
		at io.hops.metadata.util.RMUtilities.persistAppMasterRPC(RMUtilities.java:764)
		at io.hops.metadata.util.RMUtilities.persistAppMasterRPC(RMUtilities.java:741)
		at org.apache.hadoop.yarn.server.resourcemanager.ResourceTrackerService.nodeHeartbeat(ResourceTrackerService.java:459)
		at org.apache.hadoop.yarn.server.resourcemanager.ResourceTrackerService.nodeHeartbeat(ResourceTrackerService.java:443)
		at org.apache.hadoop.yarn.server.api.impl.pb.service.ResourceTrackerPBServiceImpl.nodeHeartbeat(ResourceTrackerPBServiceImpl.java:66)
		at org.apache.hadoop.yarn.proto.ResourceTracker$ResourceTrackerService$2.callBlockingMethod(ResourceTracker.java:81)
		at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:585)
		at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:928)
		at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2013)
		at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2009)
		at java.security.AccessController.doPrivileged(Native Method)
		at javax.security.auth.Subject.doAs(Subject.java:415)
		at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1548)
		at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2007)
	Caused by: com.mysql.clusterj.ClusterJUserException: Data length 16,703 too long. Column 'rpc' can only accept data of length 13,000.
		at com.mysql.clusterj.tie.NdbRecordImpl.setBytes(NdbRecordImpl.java:300)
		at com.mysql.clusterj.tie.NdbRecordOperationImpl.setBytes(NdbRecordOperationImpl.java:474)
		at com.mysql.clusterj.tie.NdbRecordOperationImpl.setBytes(NdbRecordOperationImpl.java:480)
		at com.mysql.clusterj.tie.NdbRecordSmartValueHandlerImpl.setBytes(NdbRecordSmartValueHandlerImpl.java:496)
		at com.mysql.clusterj.core.metadata.AbstractDomainFieldHandlerImpl$6.objectSetValue(AbstractDomainFieldHandlerImpl.java:858)
		at com.mysql.clusterj.core.metadata.AbstractDomainFieldHandlerImpl.objectSetValue(AbstractDomainFieldHandlerImpl.java:287)
		... 24 more

**Comment by jimdowling** [comment]
I guess the application master request/state object is > 14KB. Is that it?

If yes, the quickfix for testing is to change from varbinary to blob. However, we need to refactor the application objects into a set of tables. This is now a high priority item.
