### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by jimmyliao0422** [hopshadoop/hops#773]
I just follow this page to install this system: https://hopsworks.readthedocs.io/en/latest/installation_guide/platforms/cloud.html#

However, here is an error about SSH, how can I fix it.

```shell
[ec2-user@ip-10-0-0-12 ~]$ tail -f installation.log
INFO  [2020-03-11 06:40:14,756] se.kth.karamel.backend.ClusterManager: groups '[se.kth.karamel.backend.running.model.GroupRuntime@108a881a]'
INFO  [2020-03-11 06:40:14,757] se.kth.karamel.backend.ClusterManager: Gogo
INFO  [2020-03-11 06:40:14,757] se.kth.karamel.backend.ClusterManager: Using provider 'se.kth.karamel.common.clusterdef.Baremetal@62d415bb'
INFO  [2020-03-11 06:40:14,757] se.kth.karamel.backend.ClusterManager: Using launcher 'se.kth.karamel.backend.launcher.baremetal.BaremetalLauncher@49fe771f'
INFO  [2020-03-11 06:40:14,757] se.kth.karamel.backend.ClusterManager: Using launcher 'se.kth.karamel.backend.launcher.baremetal.BaremetalLauncher@49fe771f'
INFO  [2020-03-11 06:40:15,044] se.kth.karamel.backend.ClusterManager: \o/\o/\o/\o/\o/'Hops' MACHINES_FORKED \o/\o/\o/\o/\o/
INFO  [2020-03-11 06:40:15,044] se.kth.karamel.backend.ClusterManager: Going to serve 'SUBMIT_INSTALL_DAG'
INFO  [2020-03-11 06:40:15,044] se.kth.karamel.backend.ClusterManager: Running the DAG for 'Hops' ...
INFO  [2020-03-11 06:40:15,091] se.kth.karamel.client.api.CookbookCacheIml: 0-level cookbooks for Hops is 19
INFO  [2020-03-11 06:40:15,093] se.kth.karamel.client.api.CookbookCacheIml: 1-level cookbooks for Hops is 18
INFO  [2020-03-11 06:40:24,782] net.schmizz.sshj.transport.random.BouncyCastleRandom: Generating random seed from SecureRandom.
INFO  [2020-03-11 06:40:24,846] se.kth.karamel.backend.machines.SshMachine: 10.0.0.12: connecting ...
INFO  [2020-03-11 06:40:24,848] net.schmizz.sshj.transport.TransportImpl: Client identity string: SSH-2.0-SSHJ_0.20.0
INFO  [2020-03-11 06:40:24,857] net.schmizz.sshj.transport.TransportImpl: Server identity string: SSH-2.0-OpenSSH_7.8
INFO  [2020-03-11 06:40:25,001] se.kth.karamel.backend.machines.SshMachine: 10.0.0.12: Yey!! connected ^-^
INFO  [2020-03-11 06:40:25,044] com.hierynomus.sshj.userauth.keyprovider.OpenSSHKeyV1KeyFile: Read key type: ssh-rsa
ERROR [2020-03-11 06:40:25,047] se.kth.karamel.backend.machines.MachinesMonitor: 
! net.schmizz.sshj.common.Buffer$BufferException: Bad item length: 893165745
! at net.schmizz.sshj.common.Buffer.readString(Buffer.java:370) ~[sshj-0.20.0.jar:na]
! at com.hierynomus.sshj.userauth.keyprovider.OpenSSHKeyV1KeyFile.readUnencrypted(OpenSSHKeyV1KeyFile.java:150) ~[sshj-0.20.0.jar:na]
! at com.hierynomus.sshj.userauth.keyprovider.OpenSSHKeyV1KeyFile.readDecodedKeyPair(OpenSSHKeyV1KeyFile.java:101) ~[sshj-0.20.0.jar:na]
! at com.hierynomus.sshj.userauth.keyprovider.OpenSSHKeyV1KeyFile.readKeyPair(OpenSSHKeyV1KeyFile.java:73) ~[sshj-0.20.0.jar:na]
! at net.schmizz.sshj.userauth.keyprovider.BaseFileKeyProvider.getPublic(BaseFileKeyProvider.java:81) ~[sshj-0.20.0.jar:na]
! at net.schmizz.sshj.userauth.method.KeyedAuthMethod.putPubKey(KeyedAuthMethod.java:44) ~[sshj-0.20.0.jar:na]
! ... 15 common frames omitted
! Causing: net.schmizz.sshj.userauth.UserAuthException: Problem getting public key from com.hierynomus.sshj.userauth.keyprovider.OpenSSHKeyV1KeyFile@238b913f
! at net.schmizz.sshj.userauth.method.KeyedAuthMethod.putPubKey(KeyedAuthMethod.java:46) ~[sshj-0.20.0.jar:na]
! at net.schmizz.sshj.userauth.method.AuthPublickey.buildReq(AuthPublickey.java:62) ~[sshj-0.20.0.jar:na]
! at net.schmizz.sshj.userauth.method.AuthPublickey.buildReq(AuthPublickey.java:81) ~[sshj-0.20.0.jar:na]
! at net.schmizz.sshj.userauth.method.AbstractAuthMethod.request(AbstractAuthMethod.java:68) ~[sshj-0.20.0.jar:na]
! at net.schmizz.sshj.userauth.UserAuthImpl.authenticate(UserAuthImpl.java:72) ~[sshj-0.20.0.jar:na]
! at net.schmizz.sshj.SSHClient.auth(SSHClient.java:219) ~[sshj-0.20.0.jar:na]
! ... 10 common frames omitted
! Causing: net.schmizz.sshj.userauth.UserAuthException: Exhausted available authentication methods
! at net.schmizz.sshj.SSHClient.auth(SSHClient.java:225) ~[sshj-0.20.0.jar:na]
! at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:340) ~[sshj-0.20.0.jar:na]
! at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:359) ~[sshj-0.20.0.jar:na]
! at se.kth.karamel.backend.machines.SshMachine.connect(SshMachine.java:479) ~[karamel-core-0.6.jar:na]
! ... 7 common frames omitted
! Causing: se.kth.karamel.common.exception.KaramelException: 10.0.0.12: Authentication problem using ssh keys.
! at se.kth.karamel.backend.machines.SshMachine.connect(SshMachine.java:511) ~[karamel-core-0.6.jar:na]
! at se.kth.karamel.backend.machines.SshMachine.ping(SshMachine.java:537) ~[karamel-core-0.6.jar:na]
! at se.kth.karamel.backend.machines.MachinesMonitor.run(MachinesMonitor.java:101) ~[karamel-core-0.6.jar:na]
! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_242]
! at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_242]
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_242]
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_242]
! at java.lang.Thread.run(Thread.java:748) [na:1.8.0_242]
INFO  [2020-03-11 06:40:30,039] se.kth.karamel.backend.machines.MachinesMonitor: Sending pause signal to all machines
ERROR [2020-03-11 06:42:24,857] net.schmizz.sshj.transport.TransportImpl: Dying because - {}
! net.schmizz.sshj.transport.TransportException: Broken transport; encountered EOF
! at net.schmizz.sshj.transport.Reader.run(Reader.java:57) ~[sshj-0.20.0.jar:na]
INFO  [2020-03-11 06:42:24,857] net.schmizz.sshj.transport.TransportImpl: Disconnected - UNKNOWN
INFO  [2020-03-11 06:42:25,049] net.schmizz.sshj.transport.random.BouncyCastleRandom: Generating random seed from SecureRandom.
INFO  [2020-03-11 06:42:25,058] se.kth.karamel.backend.machines.SshMachine: 10.0.0.12: connecting ...
INFO  [2020-03-11 06:42:25,058] net.schmizz.sshj.transport.TransportImpl: Client identity string: SSH-2.0-SSHJ_0.20.0
INFO  [2020-03-11 06:42:25,066] net.schmizz.sshj.transport.TransportImpl: Server identity string: SSH-2.0-OpenSSH_7.8
INFO  [2020-03-11 06:42:25,084] se.kth.karamel.backend.machines.SshMachine: 10.0.0.12: Yey!! connected ^-^
INFO  [2020-03-11 06:42:25,123] com.hierynomus.sshj.userauth.keyprovider.OpenSSHKeyV1KeyFile: Read key type: ssh-rsa
ERROR [2020-03-11 06:42:25,124] se.kth.karamel.backend.machines.MachinesMonitor: 
! net.schmizz.sshj.common.Buffer$BufferException: Bad item length: 893165745
! at net.schmizz.sshj.common.Buffer.readString(Buffer.java:370) ~[sshj-0.20.0.jar:na]
! at com.hierynomus.sshj.userauth.keyprovider.OpenSSHKeyV1KeyFile.readUnencrypted(OpenSSHKeyV1KeyFile.java:150) ~[sshj-0.20.0.jar:na]
! at com.hierynomus.sshj.userauth.keyprovider.OpenSSHKeyV1KeyFile.readDecodedKeyPair(OpenSSHKeyV1KeyFile.java:101) ~[sshj-0.20.0.jar:na]
! at com.hierynomus.sshj.userauth.keyprovider.OpenSSHKeyV1KeyFile.readKeyPair(OpenSSHKeyV1KeyFile.java:73) ~[sshj-0.20.0.jar:na]
! at net.schmizz.sshj.userauth.keyprovider.BaseFileKeyProvider.getPublic(BaseFileKeyProvider.java:81) ~[sshj-0.20.0.jar:na]
! at net.schmizz.sshj.userauth.method.KeyedAuthMethod.putPubKey(KeyedAuthMethod.java:44) ~[sshj-0.20.0.jar:na]
! ... 15 common frames omitted
! Causing: net.schmizz.sshj.userauth.UserAuthException: Problem getting public key from com.hierynomus.sshj.userauth.keyprovider.OpenSSHKeyV1KeyFile@51594a35
! at net.schmizz.sshj.userauth.method.KeyedAuthMethod.putPubKey(KeyedAuthMethod.java:46) ~[sshj-0.20.0.jar:na]
! at net.schmizz.sshj.userauth.method.AuthPublickey.buildReq(AuthPublickey.java:62) ~[sshj-0.20.0.jar:na]
! at net.schmizz.sshj.userauth.method.AuthPublickey.buildReq(AuthPublickey.java:81) ~[sshj-0.20.0.jar:na]
! at net.schmizz.sshj.userauth.method.AbstractAuthMethod.request(AbstractAuthMethod.java:68) ~[sshj-0.20.0.jar:na]
! at net.schmizz.sshj.userauth.UserAuthImpl.authenticate(UserAuthImpl.java:72) ~[sshj-0.20.0.jar:na]
! at net.schmizz.sshj.SSHClient.auth(SSHClient.java:219) ~[sshj-0.20.0.jar:na]
! ... 10 common frames omitted
! Causing: net.schmizz.sshj.userauth.UserAuthException: Exhausted available authentication methods
! at net.schmizz.sshj.SSHClient.auth(SSHClient.java:225) ~[sshj-0.20.0.jar:na]
! at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:340) ~[sshj-0.20.0.jar:na]
! at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:359) ~[sshj-0.20.0.jar:na]
! at se.kth.karamel.backend.machines.SshMachine.connect(SshMachine.java:479) ~[karamel-core-0.6.jar:na]
! ... 7 common frames omitted
! Causing: se.kth.karamel.common.exception.KaramelException: 10.0.0.12: Authentication problem using ssh keys.
! at se.kth.karamel.backend.machines.SshMachine.connect(SshMachine.java:511) ~[karamel-core-0.6.jar:na]
! at se.kth.karamel.backend.machines.SshMachine.ping(SshMachine.java:537) ~[karamel-core-0.6.jar:na]
! at se.kth.karamel.backend.machines.MachinesMonitor.run(MachinesMonitor.java:101) ~[karamel-core-0.6.jar:na]
! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_242]
! at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_242]
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_242]
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_242]
! at java.lang.Thread.run(Thread.java:748) [na:1.8.0_242]
ERROR [2020-03-11 06:44:25,067] net.schmizz.sshj.transport.TransportImpl: Dying because - {}
! net.schmizz.sshj.transport.TransportException: Broken transport; encountered EOF
! at net.schmizz.sshj.transport.Reader.run(Reader.java:57) ~[sshj-0.20.0.jar:na]
INFO  [2020-03-11 06:44:25,067] net.schmizz.sshj.transport.TransportImpl: Disconnected - UNKNOWN
INFO  [2020-03-11 06:44:25,127] net.schmizz.sshj.transport.random.BouncyCastleRandom: Generating random seed from SecureRandom.
INFO  [2020-03-11 06:44:25,136] se.kth.karamel.backend.machines.SshMachine: 10.0.0.12: connecting ...
INFO  [2020-03-11 06:44:25,136] net.schmizz.sshj.transport.TransportImpl: Client identity string: SSH-2.0-SSHJ_0.20.0
INFO  [2020-03-11 06:44:25,144] net.schmizz.sshj.transport.TransportImpl: Server identity string: SSH-2.0-OpenSSH_7.8
INFO  [2020-03-11 06:44:25,158] se.kth.karamel.backend.machines.SshMachine: 10.0.0.12: Yey!! connected ^-^
INFO  [2020-03-11 06:44:25,199] com.hierynomus.sshj.userauth.keyprovider.OpenSSHKeyV1KeyFile: Read key type: ssh-rsa
ERROR [2020-03-11 06:44:25,200] se.kth.karamel.backend.machines.MachinesMonitor: 
! net.schmizz.sshj.common.Buffer$BufferException: Bad item length: 893165745
! at net.schmizz.sshj.common.Buffer.readString(Buffer.java:370) ~[sshj-0.20.0.jar:na]
! at com.hierynomus.sshj.userauth.keyprovider.OpenSSHKeyV1KeyFile.readUnencrypted(OpenSSHKeyV1KeyFile.java:150) ~[sshj-0.20.0.jar:na]
! at com.hierynomus.sshj.userauth.keyprovider.OpenSSHKeyV1KeyFile.readDecodedKeyPair(OpenSSHKeyV1KeyFile.java:101) ~[sshj-0.20.0.jar:na]
! at com.hierynomus.sshj.userauth.keyprovider.OpenSSHKeyV1KeyFile.readKeyPair(OpenSSHKeyV1KeyFile.java:73) ~[sshj-0.20.0.jar:na]
! at net.schmizz.sshj.userauth.keyprovider.BaseFileKeyProvider.getPublic(BaseFileKeyProvider.java:81) ~[sshj-0.20.0.jar:na]
! at net.schmizz.sshj.userauth.method.KeyedAuthMethod.putPubKey(KeyedAuthMethod.java:44) ~[sshj-0.20.0.jar:na]
! ... 15 common frames omitted
! Causing: net.schmizz.sshj.userauth.UserAuthException: Problem getting public key from com.hierynomus.sshj.userauth.keyprovider.OpenSSHKeyV1KeyFile@5bcdc89e
! at net.schmizz.sshj.userauth.method.KeyedAuthMethod.putPubKey(KeyedAuthMethod.java:46) ~[sshj-0.20.0.jar:na]
! at net.schmizz.sshj.userauth.method.AuthPublickey.buildReq(AuthPublickey.java:62) ~[sshj-0.20.0.jar:na]
! at net.schmizz.sshj.userauth.method.AuthPublickey.buildReq(AuthPublickey.java:81) ~[sshj-0.20.0.jar:na]
! at net.schmizz.sshj.userauth.method.AbstractAuthMethod.request(AbstractAuthMethod.java:68) ~[sshj-0.20.0.jar:na]
! at net.schmizz.sshj.userauth.UserAuthImpl.authenticate(UserAuthImpl.java:72) ~[sshj-0.20.0.jar:na]
! at net.schmizz.sshj.SSHClient.auth(SSHClient.java:219) ~[sshj-0.20.0.jar:na]
! ... 10 common frames omitted
! Causing: net.schmizz.sshj.userauth.UserAuthException: Exhausted available authentication methods
! at net.schmizz.sshj.SSHClient.auth(SSHClient.java:225) ~[sshj-0.20.0.jar:na]
! at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:340) ~[sshj-0.20.0.jar:na]
! at net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:359) ~[sshj-0.20.0.jar:na]
! at se.kth.karamel.backend.machines.SshMachine.connect(SshMachine.java:479) ~[karamel-core-0.6.jar:na]
! ... 7 common frames omitted
! Causing: se.kth.karamel.common.exception.KaramelException: 10.0.0.12: Authentication problem using ssh keys.
! at se.kth.karamel.backend.machines.SshMachine.connect(SshMachine.java:511) ~[karamel-core-0.6.jar:na]
! at se.kth.karamel.backend.machines.SshMachine.ping(SshMachine.java:537) ~[karamel-core-0.6.jar:na]
! at se.kth.karamel.backend.machines.MachinesMonitor.run(MachinesMonitor.java:101) ~[karamel-core-0.6.jar:na]
! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_242]
! at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_242]
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_242]
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_242]
! at java.lang.Thread.run(Thread.java:748) [na:1.8.0_242]

```

**Comment by SirOibaf** [comment]
Hi,
Please use https://community.hopsworks.ai/ for this type of issues.

I think something got corrupted with the SSH key, can you try to remove it (`/home/ec2-user/.ssh/id_rsa` and `/home/ec2-user/.ssh/id_rsa.pub`) and try again? 

However, even if you pass this phase, you won't be able to install Hopsworks correctly as we currently don't support Amazon Linux as OS - can you try with Centos or Ubuntu?
